# Numpy Arrays

In [1]:
mylist = [1,2,3]

In [2]:
import numpy as np

In [3]:
 arr = np.array(mylist)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,2) # step size (2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((5,3))  # tuple of 2,3 raw(5) ar colum (3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr = np.zeros((3,2),float)

In [13]:
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
arr = np.zeros((5,4),int)

In [15]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,15) # mane 0 theke 5 er vitorer 15ta spacepoint ber kora...

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [18]:
np.linspace(0,6,1)

array([0.])

# for identity matrix... use .eye
# here, 1 are diagonal...

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(5)  # mane andaji 5 ta random number asbe..

array([9.52129089e-01, 8.96996291e-01, 4.56909698e-01, 2.15464285e-01,
       1.86988078e-04])

In [22]:
np.random.rand(5,3)

array([[0.74163653, 0.22822557, 0.88701806],
       [0.91346723, 0.08550633, 0.39366614],
       [0.87492251, 0.15569995, 0.03168361],
       [0.16815665, 0.49333158, 0.75752715],
       [0.76294266, 0.96144857, 0.20897369]])

In [23]:
np.random.randn(2) # rand n mane normal distribution...

array([ 1.09005638, -0.59545156])

In [24]:
np.random.randn(4,4)

array([[-0.5467044 ,  0.24522746, -1.04632342, -0.81567954],
       [ 0.37509835,  0.12877947,  1.78743559,  0.53732977],
       [-0.63988866,  0.13658493, -0.52411585, -0.67813107],
       [-0.36796246, -0.42059403, -0.70316343, -0.50626562]])

In [25]:
np.random.randint(1,100)  # mane 1-100 er moddhe ekta random number dibe

51

In [26]:
np.random.randint(1,100,10)

array([28,  6,  1, 70, 69,  1, 60,  3, 35, 63])

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0,50,10)

In [30]:
ranarr

array([36, 30, 11, 26,  9, 23,  5, 49, 14, 28])

In [31]:
arr.reshape(5,5)    #mane 5*5 = 25 holo kina avabe milaya nite hobe...

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr

array([36, 30, 11, 26,  9, 23,  5, 49, 14, 28])

In [33]:
ranarr.max()

49

In [34]:
ranarr.argmax()  # koto number index e ase value ta...

7

In [35]:
ranarr.min()

5

In [36]:
ranarr.argmin()  # index location of minimum value.

6

In [37]:
arr.shape

(25,)

In [38]:
arr = arr.reshape(5,5)

In [39]:
arr.shape

(5, 5)

In [40]:
arr.dtype  # ki data type seta dekha...

dtype('int32')

# 

In [41]:
from numpy.random import randint

In [42]:
randint(2,20)

10

# for 2D array

In [44]:
arr = np.arange(12).reshape(4,3)

In [45]:
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


# for 3D array

In [46]:
c = np.arange(24).reshape(2,3,4)

In [47]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


# 1D array

In [48]:
a = np.arange(6)

In [49]:
print(a)

[0 1 2 3 4 5]
